jar cvf lib\Search.jar out\production\Bookstore\Search\Search.class
jar cvf lib\Transaction.jar out\production\Bookstore\Transaction\Transaction.class
jar cvf lib\Persistence.jar out\production\Bookstore\Persistence\Persistence.class

jar cvf bin\BookstoreCombination.jar out\production\Bookstore\BookstoreCombination.class
jar cvf bin\BookstoreGUI.jar out\production\Bookstore\BookstoreGUI.class
jar cvf bin\BookstoreServer.jar out\production\Bookstore\BookstoreServer.class