jar cvf lib\Search.jar out\production\Bookstore\Search\Search.class
jar cvf lib\Transaction.jar out\production\Bookstore\Transaction\Transaction.class
jar cvf lib\Persistence.jar out\production\Bookstore\Persistence\Persistence.class

jar cvf out\artifacts\lib\Search.jar out\production\Bookstore\Search\Search.class
jar cvf out\artifacts\lib\Transaction.jar out\production\Bookstore\Transaction\Transaction.class
jar cvf out\artifacts\lib\Persistence.jar out\production\Bookstore\Persistence\Persistence.class